from __future__ import annotations

from dataclasses import dataclass
from typing import Final

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfPower,
)


@dataclass(frozen=True)
class AtmoceSensorDescription:
    key: str
    name: str
    unique_id: str
    address: int
    data_type: str
    unit: str | None = None
    device_class: SensorDeviceClass | None = None
    state_class: SensorStateClass | None = None
    scale: float = 1.0
    precision: int | None = None
    enabled: bool = True
    scan_interval: int = 30


SENSORS: Final[list[AtmoceSensorDescription]] = [
    # Device Info / static data
    AtmoceSensorDescription(
        key="hardware_version",
        name="Atmoce Hardware Version",
        unique_id="atmoce_hardware_version",
        address=60010,
        data_type="uint16",
        enabled=False,
        scan_interval=600,
    ),
    AtmoceSensorDescription(
        key="protocol_version",
        name="Atmoce Protocol Version",
        unique_id="atmoce_protocol_version",
        address=60026,
        data_type="uint16",
        enabled=False,
        scan_interval=600,
    ),
    AtmoceSensorDescription(
        key="pv_rated_power",
        name="Atmoce PV Rated Power",
        unique_id="atmoce_pv_rated_power",
        address=60027,
        data_type="uint32",
        unit=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        precision=3,
        enabled=False,
        scan_interval=600,
    ),
    AtmoceSensorDescription(
        key="battery_rated_power",
        name="Atmoce Battery Rated Power",
        unique_id="atmoce_battery_rated_power",
        address=60029,
        data_type="uint32",
        unit=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        precision=3,
        enabled=False,
        scan_interval=600,
    ),
    AtmoceSensorDescription(
        key="battery_rated_capacity",
        name="Atmoce Battery Rated Capacity",
        unique_id="atmoce_battery_rated_capacity",
        address=60031,
        data_type="uint32",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        precision=3,
        enabled=False,
        scan_interval=600,
    ),

    # Status
    AtmoceSensorDescription(
        key="power_station_status",
        name="Atmoce Power Station Status",
        unique_id="atmoce_power_station_status",
        address=60066,
        data_type="uint16",
        scan_interval=30,
    ),
    AtmoceSensorDescription(
        key="battery_status",
        name="Atmoce Battery Status",
        unique_id="atmoce_battery_status",
        address=60067,
        data_type="uint16",
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="battery_operating_mode",
        name="Atmoce Battery Operating Mode",
        unique_id="atmoce_battery_operating_mode",
        address=60068,
        data_type="uint16",
        scan_interval=30,
    ),

    # Real-time power
    AtmoceSensorDescription(
        key="pv_power",
        name="Atmoce PV Power",
        unique_id="atmoce_pv_power",
        address=60069,
        data_type="uint32",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=1,
        precision=0,
        scan_interval=3,
    ),
    AtmoceSensorDescription(
        key="battery_power",
        name="Atmoce Battery Power",
        unique_id="atmoce_battery_power",
        address=60071,
        data_type="int32",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=1,
        precision=0,
        scan_interval=3,
    ),
    AtmoceSensorDescription(
        key="grid_power",
        name="Atmoce Grid Power",
        unique_id="atmoce_grid_power",
        address=60073,
        data_type="int32",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=1,
        precision=0,
        scan_interval=3,
    ),
    AtmoceSensorDescription(
        key="pv_reactive_power",
        name="Atmoce PV Reactive Power",
        unique_id="atmoce_pv_reactive_power",
        address=60075,
        data_type="int32",
        unit="kVAr",
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        precision=3,
        enabled=False,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="battery_reactive_power",
        name="Atmoce Battery Reactive Power",
        unique_id="atmoce_battery_reactive_power",
        address=60077,
        data_type="int32",
        unit="kVAr",
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        precision=3,
        enabled=False,
        scan_interval=10,
    ),

    # Grid voltage / current
    AtmoceSensorDescription(
        key="grid_voltage_phase_a",
        name="Atmoce Grid Voltage Phase A",
        unique_id="atmoce_grid_voltage_phase_a",
        address=60089,
        data_type="uint16",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.1,
        precision=1,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="grid_current_phase_a",
        name="Atmoce Grid Current Phase A",
        unique_id="atmoce_grid_current_phase_a",
        address=60090,
        data_type="int16",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
        precision=2,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="grid_voltage_phase_b",
        name="Atmoce Grid Voltage Phase B",
        unique_id="atmoce_grid_voltage_phase_b",
        address=60091,
        data_type="uint16",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.1,
        precision=1,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="grid_current_phase_b",
        name="Atmoce Grid Current Phase B",
        unique_id="atmoce_grid_current_phase_b",
        address=60092,
        data_type="int16",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
        precision=2,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="grid_voltage_phase_c",
        name="Atmoce Grid Voltage Phase C",
        unique_id="atmoce_grid_voltage_phase_c",
        address=60093,
        data_type="uint16",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.1,
        precision=1,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="grid_current_phase_c",
        name="Atmoce Grid Current Phase C",
        unique_id="atmoce_grid_current_phase_c",
        address=60094,
        data_type="int16",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
        precision=2,
        scan_interval=10,
    ),

    # Battery
    AtmoceSensorDescription(
        key="battery_soc",
        name="Atmoce Battery SOC",
        unique_id="atmoce_battery_soc",
        address=60095,
        data_type="uint16",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        scale=1,
        precision=0,
        scan_interval=10,
    ),
    AtmoceSensorDescription(
        key="battery_max_charge_power_limit",
        name="Atmoce Battery Max Charge Power Limit",
        unique_id="atmoce_battery_max_charge_power_limit",
        address=60200,
        data_type="uint32",
        unit=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
        precision=2,
        enabled=False,
        scan_interval=60,
    ),
    AtmoceSensorDescription(
        key="battery_max_discharge_power_limit",
        name="Atmoce Battery Max Discharge Power Limit",
        unique_id="atmoce_battery_max_discharge_power_limit",
        address=60202,
        data_type="uint32",
        unit=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
        precision=2,
        enabled=False,
        scan_interval=60,
    ),

    # Daily energy
    AtmoceSensorDescription(
        key="pv_energy_daily",
        name="Atmoce PV Energy Daily",
        unique_id="atmoce_pv_energy_daily",
        address=60164,
        data_type="uint32",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=30,
    ),
    AtmoceSensorDescription(
        key="battery_charge_energy_daily",
        name="Atmoce Battery Charge Energy Daily",
        unique_id="atmoce_battery_charge_energy_daily",
        address=60170,
        data_type="uint32",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=30,
    ),
    AtmoceSensorDescription(
        key="battery_discharge_energy_daily",
        name="Atmoce Battery Discharge Energy Daily",
        unique_id="atmoce_battery_discharge_energy_daily",
        address=60176,
        data_type="uint32",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=30,
    ),
    AtmoceSensorDescription(
        key="grid_export_energy_daily",
        name="Atmoce Grid Export Energy Daily",
        unique_id="atmoce_grid_export_energy_daily",
        address=60182,
        data_type="uint32",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=30,
    ),
    AtmoceSensorDescription(
        key="grid_import_energy_daily",
        name="Atmoce Grid Import Energy Daily",
        unique_id="atmoce_grid_import_energy_daily",
        address=60188,
        data_type="uint32",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=30,
    ),

    # Total energy
    AtmoceSensorDescription(
        key="pv_energy_total",
        name="Atmoce PV Energy Total",
        unique_id="atmoce_pv_energy_total",
        address=60160,
        data_type="uint64",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=60,
    ),
    AtmoceSensorDescription(
        key="battery_charge_energy_total",
        name="Atmoce Battery Charge Energy Total",
        unique_id="atmoce_battery_charge_energy_total",
        address=60166,
        data_type="uint64",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=60,
    ),
    AtmoceSensorDescription(
        key="battery_discharge_energy_total",
        name="Atmoce Battery Discharge Energy Total",
        unique_id="atmoce_battery_discharge_energy_total",
        address=60172,
        data_type="uint64",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=60,
    ),
    AtmoceSensorDescription(
        key="grid_export_energy_total",
        name="Atmoce Grid Export Energy Total",
        unique_id="atmoce_grid_export_energy_total",
        address=60178,
        data_type="uint64",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=60,
    ),
    AtmoceSensorDescription(
        key="grid_import_energy_total",
        name="Atmoce Grid Import Energy Total",
        unique_id="atmoce_grid_import_energy_total",
        address=60184,
        data_type="uint64",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.01,
        precision=2,
        scan_interval=60,
    ),
]
